# Generated by Django 4.0.3 on 2022-04-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=150)),
                ('log_data', models.DateTimeField(verbose_name='Data Gravada')),
            ],
        ),
    ]
